In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
### introduction to tensors

### scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([10,20])
vector

tensor([10, 20])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
### Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX [0]

tensor([7, 8])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
### TENSOR
TENSOR  = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR_1 = torch.tensor([[[1,2,3,5],
                          [4,5,6,6],
                          [6,7,8,3],
                          [1,2,3,4]],
                         [[5,6,7,5],
                         [9,5,4,2],
                         [9,7,6,1],
                          [6,5,4,7]],])
TENSOR_1.shape

torch.Size([2, 4, 4])

In [17]:
TENSOR_3 = torch.tensor([[[1,2],
                          [3,4],
                           [1,2]],
                        [[1,2],
                         [1,2],
                          [1,2]]])

TENSOR_3.shape

torch.Size([2, 3, 2])

### Random Tensors

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

random_tensor

tensor([[2.0177e-01, 9.5332e-01, 7.5927e-02, 2.7984e-01],
        [3.0811e-01, 1.0510e-01, 1.1337e-01, 6.4500e-01],
        [9.0277e-04, 6.3693e-01, 7.0512e-01, 8.1527e-01]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size =(3,224,224)) # height, width, color channles # arg = size is optional
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes & Ones

In [21]:
# zeroes
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
#Use torch.range() or torch.arange() **for future versions of pytorch
torch.range(0,10)


/tmp/ipython-input-774183273.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
one_to_11= torch.arange(1,11)
one_to_11

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.__version__

'2.8.0+cu126'

In [28]:
one_to_11= torch.arange(1,1000,20)
one_to_11

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241, 261,
        281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481, 501, 521, 541,
        561, 581, 601, 621, 641, 661, 681, 701, 721, 741, 761, 781, 801, 821,
        841, 861, 881, 901, 921, 941, 961, 981])

In [29]:
one_to_11= torch.arange(start = 0, end= 1000, step =50)
one_to_11

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [30]:
# Creating tensors like
eleven_zeroes = torch.zeros_like(input= one_to_11)
eleven_zeroes


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

In [31]:
# Float 32 tensor

float_32_tensor =  torch.tensor([3,6,9.0],
                                dtype = None, # what datatype is the tensor (e.g: Float32/Float16 etc.)
                                device= None,  # What device is your tensor on (cpu, gpu etc.)
                                requires_grad= False)  # whether or not to track gradients with this tensors operations
float_32_tensor
float_32_tensor.dtype


torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
int_64_tensor = torch.tensor([6,9,5], dtype = torch.int64)
int_64_tensor

tensor([6, 9, 5])

In [34]:
int_64_tensor * float_16_tensor

tensor([18., 54., 45.], dtype=torch.float16)

### Getting info from tensors (Tensor Attributes)
Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`

Tensors not right shape -  to get shape from a tensor, can use `tensor.shape`

Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [35]:
# Create a tensor
some_tensor  = torch.rand([3,4])
some_tensor.device

device(type='cpu')

In [36]:
# Find info from the tensor

print(some_tensor)
print(f"Datatype of tensor - {some_tensor.dtype}")
print(f"Shape of tensor - {some_tensor.shape}")
print(f"Size of tensor - {some_tensor.size()}")   # shape & size returns the same but size is a function n shape is attribute
print(f"Device of tensor - {some_tensor.device}")


tensor([[0.0262, 0.4779, 0.1970, 0.5805],
        [0.4022, 0.6501, 0.1033, 0.0683],
        [0.2845, 0.4395, 0.9721, 0.4192]])
Datatype of tensor - torch.float32
Shape of tensor - torch.Size([3, 4])
Size of tensor - torch.Size([3, 4])
Device of tensor - cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [37]:
tensor  = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor - 10

tensor([-9, -8, -7])

In [40]:
# pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise &

2. Matrix multiplication (dot product)


In [56]:
# element-wise multiplication
print(tensor, "*",  tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [57]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Matrix multiplicaation by hand & the time difference between manual coding and inbuilt function
1*1 + 2*2 + 3*3

14

In [45]:
%%time
mul = sum([tensor[i]*tensor[i] for i in range(len(tensor))])
mul

CPU times: user 1.16 ms, sys: 0 ns, total: 1.16 ms
Wall time: 1.25 ms


tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.63 ms, sys: 0 ns, total: 1.63 ms
Wall time: 1.73 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 536 µs, sys: 79 µs, total: 615 µs
Wall time: 1.17 ms


tensor(14)

In [48]:
# shape errors note: inner dimentions must match
torch.matmul(torch.rand(3,2), torch.rand(3,2))  # inner dims not maatch


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))   # inner dims match

tensor([[0.1611, 0.2938, 0.5046],
        [0.3642, 0.3779, 0.2760],
        [0.2391, 0.3105, 0.3696]])

In [58]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape  # The resulting Matrix has the shape of the outer dimentions

torch.Size([3, 3])

### One of the most common errors in deep learning : shape errors

In [59]:
# shapes for matrix multiplication

tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b = torch.tensor([[7,8],
                        [9,12],
                        [7,16]])

torch.mm(tensor_a, tensor_b)    # torch.mm is an alias of torch.matmul  # here the inner dims not match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [60]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a *transpose*

In [61]:
tensor_b

tensor([[ 7,  8],
        [ 9, 12],
        [ 7, 16]])

In [62]:
tensor_b.T, tensor_b.T.shape    # the .T is for the transpose here

(tensor([[ 7,  9,  7],
         [ 8, 12, 16]]),
 torch.Size([2, 3]))

In [63]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 23,  33,  39],
        [ 53,  75,  85],
        [ 83, 117, 131]])

In [64]:
torch.mm(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [65]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [66]:
x.dtype

torch.int64

In [67]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [70]:
# torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [71]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [72]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [73]:
# Find the position in tensor that has the minimum value with argmin() -> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [74]:
x[0]

tensor(1)

In [75]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [76]:
x[9]

tensor(91)

# Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping  - reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -  combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Permute -  Return a view of the input with dimentions permuted (swapped) in a certain way

In [77]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
# Reshaping
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [79]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
x_reshaped = x.reshape(2,9)
x_reshaped

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [81]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [82]:
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [83]:
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [84]:
x_reshaped = x.reshape(2,6)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [85]:
x_reshaped = x.reshape(6,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [86]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z [:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [89]:
# Stack tensors on top of each other
x_stacked  = torch.stack([x,x,x,x], dim=0 )
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
x_stacked  = torch.stack([x,x,x,x], dim=1 )
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [91]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
x_stacked  = torch.vstack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
x_stacked  = torch.hstack([x,x,x,x])
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
# torch.squeeze() - removes all single dimentions for a target tensor
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [95]:
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# Remove eextra dimentions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [96]:
x_reshape.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [97]:
x_reshape.squeeze().shape   # all single dimentions removed

torch.Size([9])

In [98]:
# torch.unsqueeze() - adds a single dimension to a taarget tensor at a specific dim/diimnesion
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_reshape.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape



Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([1, 9])


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [99]:
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")



New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor shape: torch.Size([1, 9])


In [100]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [101]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order. IMP NOTE : permute is a view
x_original = torch.rand(224,224,3) # [height, width, color channels (image tensor)]

# Permute the original tensor to the axis (dim) order
x_permuted = x_original.permute(2,0,1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # color, height, width


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [102]:
x_original[0,0,0] = 12.4569
x_original[0,0,0], x_permuted[0,0,0]

(tensor(12.4569), tensor(12.4569))

## Indexing (Selecting data from tensors)
* Indexing with PyTorch is similar to indexing with NumPy.

In [103]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [104]:
# let's index on our new tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
# let's index on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [106]:
# let's index on the most inner bracket (dim=2/lastdimention)
x[0][0][0]

tensor(1)

In [107]:
x[0,2,2]

tensor(9)

In [108]:
x[0][1][1]

tensor(5)

In [109]:
# You can also use ":" to select "all" of a target dimension
x[:,1]

tensor([[4, 5, 6]])

In [110]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [111]:
# Get all values of the 0 dimensoion but only the 1 index value of 1st and 2nd dimention
x[:,1,1]

tensor([5])

In [112]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [113]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [114]:
# index on x to return 9
x[:,2,2]

tensor([9])

In [115]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

 NumPy is a popular scientific Python numerical computing library.

 And because of this, PyTorch has functionality to interact with it.

 * Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
 * PyTorch tensor -> NumPy - torch.Tensor.numpy()

In [116]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # numpy array is a float64 by default n tensor is a float32 by default, when u convert the tensor will be float64 by default
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [117]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [118]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor,array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'))

In [119]:
# Change the value of array, what will this do to `tensor`?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [120]:
# Tensor to NumPy array
tensor  = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [121]:
# Change the value of tensor, what will this do to `numpy_tensor`?
tensor  = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again




In [122]:
import torch

#create two random tensors
random_tensor_A =  torch.rand(3,4)
random_tensor_B =  torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.7745, 0.1097, 0.4800, 0.3586],
        [0.6685, 0.3549, 0.5091, 0.6867],
        [0.4929, 0.8285, 0.0212, 0.4683]])
tensor([[0.1913, 0.0252, 0.5147, 0.0354],
        [0.0733, 0.6673, 0.9849, 0.4191],
        [0.9219, 0.3343, 0.2542, 0.1135]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [123]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPU's = faster computatiuon o n numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory.



In [124]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Chech for GPU access with PyTorch

In [126]:
import torch
torch.cuda.is_available()

False

In [129]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [128]:
# Count number of devices
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computatuons.

In [127]:
# Create a tensor(default on the CPU)
tensor  = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [130]:
# Moving tensor to GPU (if available)
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3])

In [131]:
## Moving tensor back to CPU
tensor_to_cpu = tensor.to(device="cpu")
tensor_to_cpu.device

device(type='cpu')

In [132]:
# If tensor is on GPU, can't transform it to NumPy
tensor_to_gpu.numpy()

array([1, 2, 3])

In [133]:
# To fix this first the tensor need to set to CPU
tensor_back_to_cpu  = tensor_to_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

In [134]:
!git config --global user.name "Hunter8T8"
!git config --global user.email "sg.sougata@gmail.com"

In [135]:
!git clone https://github.com/Hunter8T8/Neural-Networks-with-PyTorch

Cloning into 'Neural-Networks-with-PyTorch'...


In [136]:
%cd Neural-Networks-with-PyTorch

/content/Neural-Networks-with-PyTorch


In [137]:
!git checkout -b main

Switched to a new branch 'main'


In [140]:
!cp /content/pytorch_fundamentals.ipynb .

cp: cannot stat '/content/pytorch_fundamentals.ipynb': No such file or directory


In [ ]:
!cp /content/pytorch_fundamentals.ipynb
!touch README.md   # optional blank file so the branch has a commit
!git add .
!git commit -m "Initial commit on new branch"

In [ ]:
!git push origin new-branch-name

In [141]:
!ls /content

Neural-Networks-with-PyTorch  sample_data
